export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const POST_TODO_REQUEST = "POST_TODO_REQUEST";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const PATCH_TODO_REQUEST = "PATCH_TODO_REQUEST";

